version: '3.8'

services:
  psync-server:
    build: .
    ports:
      # Map port 8000 on the host to port 8000 in the container
      - "8000:8000"
    environment:
      - DATABASE_PATH=/app/db/psync.db
    volumes:
      - ./server/data:/app/data
      # Mount a directory for the database to ensure it is created as a file, not a folder
      - ./server/db:/app/db
    restart: unless-stopped # Automatically restart the container unless it is explicitly stopped