version: '3.8'

services:
  psync-server:
    build: .
    ports:
      # Map port 8000 on the host to port 8000 in the container
      - "8000:8000"
    environment:
      - DATABASE_PATH=/app/db/psync.db
      - DATA_PATH=/app/data
      - BASE_PATH=.
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
    volumes:
      - ./server/data:/app/data
      - ./server/db:/app/db
    restart: unless-stopped # Automatically restart the container unless it is explicitly stopped